#import "../prelude.typ": *

//    IMPLEMENTATION CHAPTER - WRITING GUIDE (paragraph by paragraph)

//    P1. Implementation overview
//         - Briefly restate what you built and in which language / toolchain.
//         - One or two sentences.
//         - Example (hardware):
//               "We implemented the Chisel number-representation library and its test-and-benchmark framework using the Chisel 3.5 hardware construction language, targeting Xilinx FPGAs via the Vivado toolchain."
//         - Example (software):
//               "We implemented the Scala-based number-representation library and integrated it into a Jenkins CI pipeline using sbt as the build tool, Docker for containerised test environments, and the GitHub Enterprise server for version control."

//    P2. Technology choices and justification
//         - Explain why you picked each major technology (language, framework, hardware platform, CI system, etc.) and what alternatives you considered.
//         - Example (hardware paragraph):
//               "We chose Chisel over plain Verilog because it gives us parameterizable modules, type-safe elaboration, and easy generation of Verilog for FPGA synthesis. We considered SpinalHDL but stayed with Chisel for its richer ecosystem and better integration with the Chipyard toolbox. The Xilinx Artix-7 FPGA was selected because it is readily available in the university lab and provides a good balance of logic density and DSP slices for arithmetic experiments."
//         - Example (software paragraph):
//               "We selected Scala (with sbt) because it offers functional-programming abstractions, seamless interoperability with Java libraries, and excellent support for property-based testing (ScalaCheck). We evaluated Python but opted for Scala to keep the implementation type-safe and to leverage the existing Chisel code-generation tools. Jenkins was chosen over GitHub Actions or GitLab CI because our department already maintains a shared Jenkins master with Docker agents, providing reproducible build environments."

//    P3. Core algorithms and data structures
//         - Describe the key algorithms you implemented (e.g., arithmetic operators, conversion routines, test-generation strategies) and the main data structures that hold state.
//         - Avoid line-by-line code; focus on the idea.
//         - Example (hardware):
//               "For each supported format we implemented a parameterizable ripple-carry adder, a combinational multiplier using the Baugh-Wooley algorithm for two 's-complement numbers, and a CORDIC-based square-root unit. Conversion between formats is performed by first interpreting the bit-pattern as a rational number (sign  x mantissa  x 2^exp) and then re-encoding it in the target format using rounding-to-nearest-even."
//         - Example (software):
//               "The library defines an immutable case class `NumRep[F <: Format]` that holds the bit-pattern and provides methods `+`, `-`, `*`, `/`, and `toDouble`. Each format (IEEE-754 binary32, binary64, posit-8, posit-16, unum-like) extends a sealed trait `Format` that supplies the width, exponent size, and encoding/decoding functions. Test data are generated by property-based generators that sample uniformly from the representable range and also include edge-cases (zero, infinity, NaN, smallest subnormal)."

//    P4. Problems encountered & decisions made
//         - Narrate any significant obstacles (design bugs, tooling issues, performance surprises) and the decisions you took to resolve them.
//         - Example (hardware):
//               "During early synthesis we observed that the naïve ripple-carry adder failed to meet timing at 200 MHz. We replaced it with a carry-look-ahead adder (CLA) for widths > 16 bits, which restored timing with only a modest area increase. Another issue was that the Chisel-generated Verilog contained unnamed wires that caused simulation mismatches; we fixed this by explicitly naming all internal nodes using the `suggestName` directive."
//         - Example (software):
//               "The first attempt to run the test suite inside Docker containers failed because the JVM could not access the host 's `/dev/kvm` for hardware-accelerated benchmarks. We decided to run the benchmarks directly on the Jenkins agent (bare-metal Ubuntu) while keeping the build and unit-test steps inside Docker to preserve reproducibility. This hybrid approach gave us accurate power/energy measurements via RAPL without sacrificing isolated builds."

//    P5. Environment & setup instructions
//         - Provide a concise “how to run” guide: required software versions, hardware, and any configuration steps.
//         - Example (hardware):
//               "To reproduce the results you need:
//                 • Vivado 2023.2 (or newer) for synthesis;
//                 • Chisel 3.5.6 and firrtl 1.6;
//                 • Scala 2.13.12 and sbt 1.9.8 for the test harness;
//                 • A Xilinx Artix-7 FPGA board (e.g., Nexys A7) with at least 2 GB DDR3;
//                 • Optional: Xilinx Power Estimator for post-place-and-route power numbers.
//               Clone the repository, run `sbt test` to execute the unit-test harness, then `make synth` to invoke the Vivado synthesis scripts."
//         - Example (software):
//               "To reproduce the results you need:
//                 • Docker Engine 24.0+;
//                 • OpenJDK 17 (for the sbt build);
//                 • sbt 1.9.8;
//                 • Jenkins 2.452 with the Docker plugin enabled;
//                 • A Linux x86-64 machine with RAPL support (Intel i7-12700K or newer) for energy measurements;
//                 • Git (≥ 2.40) for cloning.
//               After cloning, execute `./jenkins/jenkinsfile.sh` locally or push to the GitHub-Enterprise repository to trigger the Jenkins pipeline, which will publish the test and benchmark results as build artifacts."

//    P6. Pseudocode & summary tables (optional)
//         - Present high-level pseudocode for the main algorithms or a summary table of configurable parameters (e.g., format widths, iteration counts).
//         - Do not dump raw source files.
//         - Example (hardware pseudocode):
//               "Pseudocode for the parameterizable multiplier:
//               ```python
//                 function multiply(a, b, w):
//                   // w = total bit-width
//                   // interpret a,b as signed two 's-complement integers
//                   prod = a * b
//                   // truncate to w bits (dropping overflow)
//                   return prod & ((1<<w)-1)"
//               ```"
//         - Example (hardware table):
//               "Summary table of supported formats:
//                 #table(
//   columns: (5cm, 2cm, 3cm, 4cm),
//   align: (left, center, center, left),
//   [*Format*], [*Width*], [*Exponent bits*], [*Notes*],
//   [Fixed-point (Q8.8)], [16], [-], [ … ],
//   [IEEE-754 binary32], [32], [8], [ … ],
//   [Posit-8], [8], [0], [ … ],
//   [Posit-16], [16], [1], [ … ]
// )"
//         - Example (software pseudocode):
//               "Pseudocode for the posit addition operation:
//               ```python
//                 function addPosit(p, q, es):
//                   // decode to signed regime, exponent, fraction
//                   v = decode(p, es); w = decode(q, es);
//                   r = v + w;
//                   return encode(r, es);"
//               ```"
//         - Example (software table):
//               "Summary table of format parameters:
//                 #table(
//   columns: (5cm, 3cm, 4cm, 4cm),
//   align: (left, center, center, left),
//   [*Format*], [*Total bits*], [*Exponent size (es)*], [*Notes*],
//   [IEEE-754 binary32], [32], [8], [ … ],
//   [IEEE-754 binary64], [64], [11], [ … ],
//   [Posit-8], [8], [0], [ … ],
//   [Posit-16], [16], [1], [ … ],
//   [Unum-like], [32], [-], [ … ]
// )"
