#import "../prelude.typ": *

//    IMPLEMENTATION CHAPTER - WRITING GUIDE (paragraph by paragraph)

//    P1. Implementation overview
//         - Briefly restate what you built and in which language / toolchain.
//         - One or two sentences.
//         - Example (hardware):
//               "We implemented the Chisel number-representation library and its test-and-benchmark framework using the Chisel 3.5 hardware construction language, targeting Xilinx FPGAs via the Vivado toolchain."
//         - Example (software):
//               "We implemented the Scala-based number-representation library and integrated it into a Jenkins CI pipeline using sbt as the build tool, Docker for containerised test environments, and the GitHub Enterprise server for version control."

//    P2. Technology choices and justification
//         - Explain why you picked each major technology (language, framework, hardware platform, CI system, etc.) and what alternatives you considered.
//         - Example (hardware paragraph):
//               "We chose Chisel over plain Verilog because it gives us parameterizable modules, type-safe elaboration, and easy generation of Verilog for FPGA synthesis. We considered SpinalHDL but stayed with Chisel for its richer ecosystem and better integration with the Chipyard toolbox. The Xilinx Artix-7 FPGA was selected because it is readily available in the university lab and provides a good balance of logic density and DSP slices for arithmetic experiments."
//         - Example (software paragraph):
//               "We selected Scala (with sbt) because it offers functional-programming abstractions, seamless interoperability with Java libraries, and excellent support for property-based testing (ScalaCheck). We evaluated Python but opted for Scala to keep the implementation type-safe and to leverage the existing Chisel code-generation tools. Jenkins was chosen over GitHub Actions or GitLab CI because our department already maintains a shared Jenkins master with Docker agents, providing reproducible build environments."

//    P3. Core algorithms and data structures
//         - Describe the key algorithms you implemented (e.g., arithmetic operators, conversion routines, test-generation strategies) and the main data structures that hold state.
//         - Avoid line-by-line code; focus on the idea.
//         - Example (hardware):
//               "For each supported format we implemented a parameterizable ripple-carry adder, a combinational multiplier using the Baugh-Wooley algorithm for two 's-complement numbers, and a CORDIC-based square-root unit. Conversion between formats is performed by first interpreting the bit-pattern as a rational number (sign  x mantissa  x 2^exp) and then re-encoding it in the target format using rounding-to-nearest-even."
//         - Example (software):
//               "The library defines an immutable case class `NumRep[F <: Format]` that holds the bit-pattern and provides methods `+`, `-`, `*`, `/`, and `toDouble`. Each format (IEEE-754 binary32, binary64, posit-8, posit-16, unum-like) extends a sealed trait `Format` that supplies the width, exponent size, and encoding/decoding functions. Test data are generated by property-based generators that sample uniformly from the representable range and also include edge-cases (zero, infinity, NaN, smallest subnormal)."

//    P4. Problems encountered & decisions made
//         - Narrate any significant obstacles (design bugs, tooling issues, performance surprises) and the decisions you took to resolve them.
//         - Example (hardware):
//               "During early synthesis we observed that the naïve ripple-carry adder failed to meet timing at 200 MHz. We replaced it with a carry-look-ahead adder (CLA) for widths > 16 bits, which restored timing with only a modest area increase. Another issue was that the Chisel-generated Verilog contained unnamed wires that caused simulation mismatches; we fixed this by explicitly naming all internal nodes using the `suggestName` directive."
//         - Example (software):
//               "The first attempt to run the test suite inside Docker containers failed because the JVM could not access the host 's `/dev/kvm` for hardware-accelerated benchmarks. We decided to run the benchmarks directly on the Jenkins agent (bare-metal Ubuntu) while keeping the build and unit-test steps inside Docker to preserve reproducibility. This hybrid approach gave us accurate power/energy measurements via RAPL without sacrificing isolated builds."

//    P5. Environment & setup instructions
//         - Provide a concise “how to run” guide: required software versions, hardware, and any configuration steps.
//         - Example (hardware):
//               "To reproduce the results you need:
//                 • Vivado 2023.2 (or newer) for synthesis;
//                 • Chisel 3.5.6 and firrtl 1.6;
//                 • Scala 2.13.12 and sbt 1.9.8 for the test harness;
//                 • A Xilinx Artix-7 FPGA board (e.g., Nexys A7) with at least 2 GB DDR3;
//                 • Optional: Xilinx Power Estimator for post-place-and-route power numbers.
//               Clone the repository, run `sbt test` to execute the unit-test harness, then `make synth` to invoke the Vivado synthesis scripts."
//         - Example (software):
//               "To reproduce the results you need:
//                 • Docker Engine 24.0+;
//                 • OpenJDK 17 (for the sbt build);
//                 • sbt 1.9.8;
//                 • Jenkins 2.452 with the Docker plugin enabled;
//                 • A Linux x86-64 machine with RAPL support (Intel i7-12700K or newer) for energy measurements;
//                 • Git (≥ 2.40) for cloning.
//               After cloning, execute `./jenkins/jenkinsfile.sh` locally or push to the GitHub-Enterprise repository to trigger the Jenkins pipeline, which will publish the test and benchmark results as build artifacts."

//    P6. Pseudocode & summary tables (optional)
//         - Present high-level pseudocode for the main algorithms or a summary table of configurable parameters (e.g., format widths, iteration counts).
//         - Do not dump raw source files.
//         - Example (hardware pseudocode):
//               "Pseudocode for the parameterizable multiplier:
//               ```python
//                 function multiply(a, b, w):
//                   // w = total bit-width
//                   // interpret a,b as signed two 's-complement integers
//                   prod = a * b
//                   // truncate to w bits (dropping overflow)
//                   return prod & ((1<<w)-1)"
//               ```"
//         - Example (hardware table):
//               "Summary table of supported formats:
//                 #table(
//   columns: (5cm, 2cm, 3cm, 4cm),
//   align: (left, center, center, left),
//   [*Format*], [*Width*], [*Exponent bits*], [*Notes*],
//   [Fixed-point (Q8.8)], [16], [-], [ … ],
//   [IEEE-754 binary32], [32], [8], [ … ],
//   [Posit-8], [8], [0], [ … ],
//   [Posit-16], [16], [1], [ … ]
// )"
//         - Example (software pseudocode):
//               "Pseudocode for the posit addition operation:
//               ```python
//                 function addPosit(p, q, es):
//                   // decode to signed regime, exponent, fraction
//                   v = decode(p, es); w = decode(q, es);
//                   r = v + w;
//                   return encode(r, es);"
//               ```"
//         - Example (software table):
//               "Summary table of format parameters:
//                 #table(
//   columns: (5cm, 3cm, 4cm, 4cm),
//   align: (left, center, center, left),
//   [*Format*], [*Total bits*], [*Exponent size (es)*], [*Notes*],
//   [IEEE-754 binary32], [32], [8], [ … ],
//   [IEEE-754 binary64], [64], [11], [ … ],
//   [Posit-8], [8], [0], [ … ],
//   [Posit-16], [16], [1], [ … ],
//   [Unum-like], [32], [-], [ … ]
// )"

Pornind de la arhitectura generală prezentată în capitolul anterior, a fost implementat un sistem de SLAM bazat pe scan matching, cu un accent puternic pe front-end-ul unui sistem general de SLAM pentru estimarea poziției prin scan matching și construirea unei hărți, fără a include totuși o componentă de închiderea buclelor.
Majoritatea funcționalității este concentrată în nodul map_node care înglobează componenta front end a unui sistem SLAM de bază.

== 4.1 Tehnologii alese

Precum a fost prezentat în capitolul 2 al lucrării, a fost aleasă dezvoltarea sistemului pe ROS 2, fiind cel mai folosit framework de middleware pentru aplicațiile de roboți mobili.
Fiind un framework bazat pe o metodologie de dezvoltare distribuită, componentele pot să fie grupate pe noduri pentru a ușura dezvoltarea individuală și oferă posibilitatea înlocuirii ușoare a anumitor componente.

Implementarea se putea realiza fie în C++ fie în Python, și a fost aleasă implementarea soluției în Python din motive ce țin în primul rând de complexitatea mai scăzută a procesului de dezvoltare efectivă, dar mai ales datorită numeroaselor biblioteci care puteau fi utilizate pentru a implementa funcționalitățile necesare.
Bineînțeles, această decizie a venit cu principalul dezavantaj, anume faptul că o implementare în Python va avea performanțe de viteză mai scăzute față de o implementare în C++.
În viitoare versiuni, se poate face schimbarea de limbaj, cel puțin a unor componente pentru a oferi o performanță mai bună pentru sistem.

Cea mai importantă parte a sistemului este componenta de scan matching.
Dacă algoritmul de GICP a fost ales pentru faptul că îmbină ambele abordări de ICP, point to point și point to map, în același cadru probabilistic, oferind de asemenea o robustețe și o precizie mai ridicată, biblioteca de small_gicp a fost aleasă pentru viteza superioară față de alte biblioteci precum PCL.

Pentru a implementa componenta de EKF pentru estimarea poziției a fost aleasă folosirea pachetului robot_localization @robot_localization.
Acesta oferă o implementare a unui nod cu un EKF, configurabil, pentru a putea fuziona datele senzorilor, în orice configurație dorită de către utilizator.

== 4.2 Structuri de date

Forma aleasă pentru reprezentarea hărții a fost cea de occupancy grid.
Aceasta este o formă intuitivă de a reprezenta mediul înconjurător, în care fiecare celulă conține o estimare a stării de ocupat sau liber a poziției din mediu corespunzătoare celulei.

Pentru simplitate în implementare a fost luată decizia ca harta să fie de o dimensiune suficient de mare pentru a putea reprezenta suficiente medii pentru testarea algoritmului.
Acest lucru nu vine cu foarte multe dezavantaje, fiind vorba doar de o matrice, nu crește cu mult costul de stocare a acesteia.
Operațiile de actualizare a matricei se folosesc de array-uri NumPy, deci aceste operații sunt vectorizate și se realizează eficient și nu produc probleme de performanță.
Pentru aceasta s-a ales ca harta să fie dimensionată la 30 x 30 m.
Pentru un grad suficient de detalii și pentru a păstra performanțele sistemului la un nivel bun a fost aleasă o rezoluție de 0.05, ceea ce înseamnă că matricea care reprezintă harta mediului este o matrice pătratică de 600 x 600 celule, ceea ce nu prezintă o problemă pentru majoritatea sistemelor.
Matricea este centrată astfel încât originea sistemului de coordonate map să corespundă centrului matricei.

Modul de reprezentare a stărilor celulelor este cel bazat pe log-odds.
A fost aleasă această abordare pentru a putea cuantifica impactul fiecărei scanări într-un mod care să permită cuantizarea informației cât mai corespunzător.
După extragerea setului de puncte din scanarea actuală, se găsesc coordonatele celulelor corespunzătoare.
Valorilor acestor celule li se adună +0.2 pentru a semnifica că au fost detectate încă o dată.
Având acest set de puncte, apoi se execută algoritmul lui Bresenham pornind de la poziția actuală a robotului și se obțin celulele care sunt libere, adică cele prin care trece linia de la robot la obstacol.
Acestor celule le este scăzută 0.1.
Valorile corespunzătoare descoperirii unei celule ocupate sau libere au fost alese experimental, totuși având în vedere principiul că detecția unui spațiu ocupat oferă mai multă informație decât detecția unei celule goale, motiv pentru care ponderea oferită este mai mare.

Valorile celulelor sunt trunchiate în intervalul $[-6, 6]$ pentru a putea asigura revenirea unei celule în cazul în care o celulă este detectată eronat ca fiind liberă sau ocupată, prevenind creșterea continuă a valorilor.

Pentru a putea realiza corecția distorsiunii de mișcare, este necesar să se cunoască poziția robotului pe toată durata achiziției de date.
Din acest motiv se păstrează un buffer al estimărilor din trecut, de forma $(x, y, "yaw")$, cu o dimensiune de 400 de elemente, care păstrează doar pozițiile recente, cele cu o vechime mai mică de o secundă.
Buffer-ul este implementat sub formă de deque (double ended queue) deoarece oferă operații ce se realizează în timp constant, adăugarea unei noi estimări și eliminarea unei estimări vechi.

== 4.3 Estimarea poziției

Primul pas al soluției este estimarea poziției actuale, sub forma unei predicții. 
Întrucât datele primite, fie de la senzori, sau de la nodul de EKF nu se află în același sistem de coordonate, la fiecare poziție nou primită se calculează diferența între ultima poziție primită și cea actuală pentru a putea estima mișcarea. 
Cu această estimare a mișcării, se poate crea o primă predicție a poziției, fiind aplicată ultimei estimări primite de la componenta de scan matching.
Aceasta va fi poziția care va fi folosită inițial în restul soluției până se ajunge la etapa de scan matching, care va furniza o ultimă estimare a poziției.

Datele brute de la LiDAR sunt primite sub forma unor distanțe, fiecare corespunzătoare unui unghi spre care a fost trimis fasciculul de lumină.
Sunt eliminate valorile care nu se află în plaja de valori a senzorului de LiDAR, în cazul robotului TurtleBot3 Burger, plaja de valori este $[0.12 m, 3.5 m] $.
Pentru fiecare fascicul este calculat unghiul corespunzător, cunoscând unghiul minim la care emite senzorul, precum și incrementul de unghi și indexul valorii în șirul primit de la senzor.
Acestea sunt transformate în coordonate cu ajutorul @eq:point_cloud.
Din moment ce senzorul nu se află în centrul robotului, punctele obținute primesc o corecție de poziție care corespunde transformării de la planul robotului la cel al senzorului.

Din moment ce senzorul se rotește pentru a obține toate măsurătorile, în timpul deplasării apare o mică distorsiune.
Pentru a rezolva această distorsiune se folosește interpolarea pozițiilor, prezentată în capitolul 2.

În principiu fiecărui fascicul i se acordă un moment de timp corespunzător.
Pentru fiecare fascicul, fiecare cu un moment de timp asociat, se extrag pozițiile corespunzătoare din buffer-ul de poziții, ale căror momente de timp asociate mărginesc momentul fasciculului.
Căutarea se realizează folosind funcția din numpy searchsorted care localizează în același timp atât momentul precedent cât și cel ulterior.

După ce se obține poziția, fiecare punct este transformat din sistemul de referință al robotului în sistemul global, după care se revine în sistemul de referință al robotului, astfel eliminându-se distorsiunea cauzată de mișcare.

Componenta principală a sistemului este componenta de scan matching, care aliniază setul de puncte obținut de la LiDAR cu harta care a fost creată până în acel moment.
Harta se reconstruiește prin extragerea din occupancy grid-ul care a fost construit la iterația trecută a celulelor care conțin valori mai mari decât 1, valoare aleasă pentru a putea extrage suficiente puncte pentru a avea un set suficient de mare de puncte pentru a obține rezultate corecte în urma scan matching-ului.

Punctele din ambele seturi sunt preprocesate înainte de a se face alinierea.
Acestea trec printr-o etapă de subeșantionare la o rezoluție de 0.025 m pentru uniformizarea punctelor și pentru a accelera alinierea efectivă.
Alinierea se face folosind GICP, care este configurat să accepte o distanță maximă de corespondență de 0.2 m și maxim 15 iterații pentru a converge.
Rezultatul este poziția reală a robotului, doar dacă poziția rezultată nu diferă prea mult de cea estimată. Dacă diferența între predicția făcută la început și cea din urma etapei de scan matching este mai mare de 0.2 m sau orientarea diferă cu 0.09 radiani, adică aproximativ 5 grade, estimarea poziției rămâne predicția de la începutul procesului.

După prima aliniere, în cazul în care a fost acceptată, folosind poziția nou estimată, se reconstruiește setul de puncte în aceeași modalitate ca înainte, se reface interpolarea pozițiilor și se obține un nou set de puncte, care va fi apoi aliniat față de setul precedent, corespunzător primei interpolări liniare.

Scopul acestei a doua etape de scan matching este de a obține o poziție mai exactă, așa că etapa de GICP este configurată să fie mult mai strictă comparativ cu prima, anume: distanța maximă de corespondență nu trebuie să depășească mai mult de 0.1 m și algoritmul trebuie să conveargă în cel mult 10 iterații.
Rezultatul este din nou comparat cu predicția, însă de data aceasta trebuie să îndeplinească niște criterii mai stricte: translație sub 0.1 m și rotație de maxim 0.05 radiani, aproximativ 3 grade.
Dacă trece și de aceste criterii, noua poziție devine estimarea finală a sistemului și în baza acesteia se actualizează harta.

Valorile din interiorul occupancy grid-ului sunt apoi transformate în probabilități folosind @eq:log-odds.
În funcție de probabilități, conținutul hărții este transformat pentru ca harta să poată fi apoi vizualizată corespunzător, în funcție de probabilitatea de a fi ocupată.
Astfel, celulele cu o probabilitate mai mare de 70% primesc valoarea 100, corespunzătoare statusului de ocupată, cele cu probabilități mai mici de 20% primesc valoarea 0, libere și cele cu probabilități între aceste praguri primesc valoarea -1, echivalente stării de necunoscut. 
S-a ales ca valorile hărții să nu fie transmise mai departe sub forma de probabilități pentru a ușura interpretarea și vizualizarea hărții rezultate.
Dacă se păstrau probabilitățile și se scalau să se afle în plaja de valori acceptată de mesajul care trebuie trimis (0-100), apărea un efect de gradient pe hartă, lucru care putea crea anumite probleme în viitor, de pildă la planificarea rutelor.

== 4.4 Configurare EKF

Fiind vorba de un nod configurabil, se pot alege diferite topic-uri la care să se aboneze pentru a prelua datele.
Scopul fiind ca nodul de EKF să producă o estimare a poziției în baza datelor primite de la unitatea inerțială și de la senzorii odometrici ai roților.

TurtleBot3 este un robot cu tracțiune diferențiată.
Are două roți, fiecare controlată individual de către un motor.
Acesta se rotește prin aplicarea unor comenzi diferite fiecărui motor, dacă se dorește ca acesta să își schimbe orientarea se vor transmite comenzi opuse roților, sensul de rotație fiind dat de motorul care primește comanda negativă.
Din această cauză, robotul se va deplasa mereu pe axa OX locală, indiferent de direcția de deplasare privită din sistemul de coordonate global.

De asemenea, fiind vorba de un mediu fără schimbări de altitudine, filtrul este setat să funcționeze în modul bidimensional (two_d_mode: true), astfel sunt forțate ca valorile axei Z, ale unghiurilor de roll și pitch să fie 0.
Aceasta duce la o robustețe mai mare, împiedicând filtrul să estimeze poziții care nu sunt posibile fizic vorbind în constrângerile mediului.

Cu aceste considerente au fost alese informațiile care vor fi luate în considerare de filtru pentru estimarea poziției.
Se pot prelua de la fiecare sursă informații cu privire la: poziția și orientarea robotului, viteza liniară, viteza unghiulară și accelerația unghiulară.
Pe parcursul configurării s-au testat mai multe posibile combinații ale surselor de informație.
Varianta finală la care s-a ajuns este cea în care se fuzionează viteza liniară pe axa X, $v_x$, viteza unghiulară în jurul unghiului yaw, $v_"yaw"$ provenite de la senzorii odometrici ai roților și viteza unghiulară în jurul unghiului yaw provenită de la unitatea inerțială.
Includerea accelerațiilor nu s-a dovedit a aduce un impact pozitiv asupra rezultatelor.
Experimental s-a observat că includerea unghiului yaw provenit de la IMU, care ar fi trebuit să ofere cea mai bună estimare a orientării robotului a avut un impact negativ în estimarea poziției.

Problema prezentată de utilizarea valorilor efective ale poziției și orientării constă în faptul că estimările efective primite sunt calculate pe principiul de dead-reckoning, integrarea vitezelor înregistrate, ceea ce duce la o inevitabilă acumulare a erorilor în urma integrării; vitezele în schimb sunt fiabile pentru a obține o estimare bună în urma EKF.

Pentru a proteja estimarea de valorile aberante a fost introdusă o constrângere bazată pe distanța Mahalanobis, conform căreia se va respinge o măsurătoare în cazul în care sunt depășite 15 deviații standard.
Dacă sunt furnizate valori de către senzori care diferă prea mult de comportamentul așteptat, acestea sunt ignorate.

În plus, experimental au fost încercate diferite valori pentru matricea de covarianță a zgomotului de proces, pentru fiecare termen.
Valorile controlează nivelul de încredere avut de către model în măsurătorile primite.

// #pagebreak()

== 4.5 Probleme întâlnite

Pe parcursul dezvoltării soluției au apărut diverse probleme care au necesitat adeseori schimbarea abordării.
Una dintre primele astfel de probleme întâlnite a fost legată de estimarea poziției folosind măsurătorile primite de la senzori.
Principiul de bază fiind integrarea vitezelor detectate, care inevitabil ducea la acumularea de erori care în timp ducea la pierderea totală a poziției.
Datele provenite de la odometria roților erau în mod special predispuse acestor probleme.
Deoarece soluția ar fi presupus să fie implementată o componentă mai complexă pentru a obține aceleași date care erau calculate și de robot nativ, a fost aleasă folosirea directă a acelor date brute, care totuși avea pe termen lung aceeași problemă.
Tocmai apariția drift-ului a creat nevoia de aplicare a unei corecții asupra poziției pentru a păstra integritatea hărților și a estimărilor, motiv pentru care a fost aleasă introducerea unei componente de scan matching.

Inițial, a fost planificată implementarea acestei componente într-o manieră de bază folosind ICP și o abordare de tip scan to scan matching.
Prima problemă întâmpinată are legătură cu faptul că setul de puncte era prea dens și nu se detecta mișcarea.
Din acest motiv a fost introdusă etapa de subeșantionare, care a produs seturi de puncte care să poată fi aliniate corect.

Altă problemă, fundamentală este faptul că în această abordare, în urma scan matching-ului, se obține o transformare care reprezintă cât s-a deplasat robotul între cele două seturi de puncte.
Această abordare nu este cu nimic fundamental diferită de abordarea de dead-reckoning.
Erorile apărute la fiecare etapă de ICP sunt acumulate și poziția se pierde destul de repede.
Se ajungea și în cazul în care, când robotul stătea oprit, seturile de puncte nu erau tocmai identice, rezultând o transformare mică între seturi, care se acumula, și poziția estimată se deplasa pe când robotul nu o făcea în realitate.
Schimbarea algoritmului în varianta de Point to Plane ICP nu a ajutat pentru a rezolva problema.

Singura soluție a fost trecerea la o abordare de tip scan to map matching, în care se compară setul de puncte cu întreaga hartă pentru a putea fi obținută o estimare corectă.
În acest caz, în urma scan matching-ului se va obține poziția robotului în cadrul sistemului global de referință.
Acest aspect a dus la nevoia de refactorizare a celorlalte componente ale sistemului.
Algoritmul ales pentru aceasta a fost GICP, din motivele discutate anterior.

După aceasta problemele nu au mai fost la fel de grave, din perspectiva funcționării sistemului, acestea două fiind principalele probleme care au împiedicat obținerea oricărui fel de rezultat pozitiv.

Alte probleme mai serioase au fost cele care au apărut în momentul în care a fost adăugat nodul de EKF, deoarece cu toate soluțiile anterioare, poziția estimată tot nu era stabilă și era predispusă erorilor, lucru care ducea inevitabil la hărți de o calitate mai scăzută.

Inițial rezultatele cu nodul de EKF nu erau cu nimic mai bune, poate chiar mai slabe calitativ, lucru care s-a dovedit a se datora lipsei covarianțelor pentru mesajele de la senzorii odometrici, ceea ce făcea modelul să considere că măsurătorile primite erau perfecte, lucru care afecta masiv performanțele.
Adăugarea unor covarianțe a dus la rezolvarea problemei și la posibilitatea de configurare corespunzătoare a nodului responsabil de EKF.

O ultimă problemă specifică a fost existența distorsiunii cauzate de mișcarea robotului în măsurătorile senzorului de LiDAR.
Cu toate că efectele erau cel mai puțin grave dintre cele menționate, hărțile rezultate aveau probleme vizibile, mai ales cu privire la grosimea obstacolelor în reprezentarea de pe hartă.
Acestea sunt datorate fix distorsiunilor din setul de puncte care se propagă apoi atât în hartă cât și în poziția robotului.
Componenta de distorsiune folosind interpolarea liniară a fost soluția care a rezolvat această problemă.